# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [];

  # To get UUID data: [$ lsblk -o NAME,FSSIZE,FSTYPE,FSUSED,PKNAME,UUID]

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/cba3fd87-dd87-4f87-afa0-6fbd30cbff8f";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/A0E3-108C";
      fsType = "vfat";
    };

    "/home/rec1dite/.mnt/ub1tu" = {
      device = "/dev/disk/by-uuid/4cc0ea5d-2d88-4f62-a013-e024a2d3960a";
      fsType = "ext4";
    };

    # See [https://nixos.wiki/wiki/NTFS]
    "/home/rec1dite/.mnt/heap" = {
      device = "/dev/disk/by-uuid/3CC8433BC842F2A6";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ]; # Obtain UID by: [$ id -u rec1dite] or [$ echo $UID]
    };
	# -      device = "/dev/disk/by-uuid/2C6E23E36E23A494";
	# +      device = "/dev/disk/by-uuid/3CC8433BC842F2A6";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
